project_id = "ryhhskssaplqakovldlp"

[functions.test-openai]
verify_jwt = false

[functions.ask]
verify_jwt = true

[functions.test-ask]
verify_jwt = false

[functions.cashfree-webhook]
verify_jwt = false

[functions.generate-code]
verify_jwt = true
